apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: expense-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
        - name: backend
          image: your-dockerhub-username/expense-tracker-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://alpha:12345@cluster0.ngen05o.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
